language: go
go:
  - 1.5

env:
  global:
    - PATH="$GOPATH/bin:$PATH"
    - RELEASES_PATH=/tmp/releases

before_deploy:
  - go get github.com/laher/goxc
  - goxc -tasks 'xc archive' -bc 'windows darwin linux' -d "$RELEASES_PATH" -resources-include 'README*'

deploy:
  provider: releases
  api_key:
    secure: m1OYf5TJHtt1/guFqBknLlmWJ6W+Hj6Ko0i2i+12QlOorek7zJmtxpVGv1fMXkDHzOhgr/oDuavEX0fA/ZfxquXO0wndxrfq+v2kgMOMAjjmNGS4DRrR0/TG7RQuu19eqgUhq3pn3Yx6tl/4p7tNWYzV7z0pxcRPQ+k3YqWu+DpHN3nTrDBpKhR5/sT7OkmYYcX3u+YIWY0EuBQzTieFdIFu/L8/psyEtOrZSZHDVr9QO89Y/cVqOt6XVWf2A2V31qyimYlDS8/Nf3Uxxcij5vewifT1Li5a0YEax85O5vRus87MnxvL7SXcp7AleRA2SKRfFbpYp9hheJvbjlSBJdWg1aLrm8lHcXfUOkzDgnbbujW+78VcvE1JbPpqc9gb/bs00LLgkIsmUo7P3MqkpPZSHn8xHqbeb0npBcJ0eemFE9QlDtvphpeJo+ZR2wpAyjUwABMCngr4L8xZBJrWM5Ma1OzeaJlkBWWjF2H+k2PRih+toNansO0AVqW0K0JNjQmwwYWI7Th2QCQrpXwSfbKbtN66bZQylvuLzo6+Fr3V46coAvdwhtT7tVW4hwkQXKWx1xnyNUc1OWnCAaBLANMzmbJBQhzqEiHCQD52gOb/oA+7LnCSnEiDrcXvr2YBkSdpE3xNs0PFZiTmJM5e4erNXVZpSjbag0iFbUGQJf4=
  file:
    - $RELEASES_PATH/snapshot/catn_windows_386.zip
    - $RELEASES_PATH/snapshot/catn_windows_amd64.zip
    - $RELEASES_PATH/snapshot/catn_darwin_386.zip
    - $RELEASES_PATH/snapshot/catn_darwin_amd64.zip
    - $RELEASES_PATH/snapshot/catn_linux_386.tar.gz
    - $RELEASES_PATH/snapshot/catn_linux_amd64.tar.gz
    - $RELEASES_PATH/snapshot/catn_linux_arm.tar.gz
  on:
    repo: kusabashira/catn
    tags: true
